# Generated by Django 5.0.4 on 2024-04-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bilqram', '0003_blog_alter_user_profile_pic_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parblog',
            new_name='par_blog',
        ),
    ]
