# Generated by Django 5.0.4 on 2024-04-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bilqram', '0004_rename_parblog_comment_par_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bilqram.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bilqram.user')),
            ],
        ),
    ]
